// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Goal struct {
	ID          string
	Title       string
	Description *string
	Status      string
	Created     int64
}

type Idea struct {
	ID      string
	Text    string
	Created int64
}

type Schedule struct {
	Date   string
	Focus  string
	Blocks *string
}

type Task struct {
	ID      string
	Title   string
	GoalID  *string
	Status  string
	Created int64
	Due     *string
}
