// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, title, description, status, created)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, description, status, created
`

type CreateGoalParams struct {
	ID          string
	Title       string
	Description *string
	Status      string
	Created     int64
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Created,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Created,
	)
	return i, err
}

const createIdea = `-- name: CreateIdea :one
INSERT INTO ideas (id, text, created)
VALUES (?, ?, ?)
RETURNING id, text, created
`

type CreateIdeaParams struct {
	ID      string
	Text    string
	Created int64
}

func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error) {
	row := q.db.QueryRowContext(ctx, createIdea, arg.ID, arg.Text, arg.Created)
	var i Idea
	err := row.Scan(&i.ID, &i.Text, &i.Created)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, title, goal_id, status, created, due)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, title, goal_id, status, created, due
`

type CreateTaskParams struct {
	ID      string
	Title   string
	GoalID  *string
	Status  string
	Created int64
	Due     *string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.GoalID,
		arg.Status,
		arg.Created,
		arg.Due,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.GoalID,
		&i.Status,
		&i.Created,
		&i.Due,
	)
	return i, err
}

const getGoal = `-- name: GetGoal :one
SELECT id, title, description, status, created FROM goals
WHERE id = ?
`

func (q *Queries) GetGoal(ctx context.Context, id string) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Created,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT date, focus, blocks FROM schedule
WHERE date = ?
`

func (q *Queries) GetSchedule(ctx context.Context, date string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, date)
	var i Schedule
	err := row.Scan(&i.Date, &i.Focus, &i.Blocks)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, goal_id, status, created, due FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.GoalID,
		&i.Status,
		&i.Created,
		&i.Due,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, title, description, status, created FROM goals
ORDER BY created DESC
`

func (q *Queries) ListGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByStatus = `-- name: ListGoalsByStatus :many
SELECT id, title, description, status, created FROM goals
WHERE status = ?
ORDER BY created DESC
`

func (q *Queries) ListGoalsByStatus(ctx context.Context, status string) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeas = `-- name: ListIdeas :many
SELECT id, text, created FROM ideas
ORDER BY created DESC
LIMIT ?
`

func (q *Queries) ListIdeas(ctx context.Context, limit int64) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, listIdeas, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(&i.ID, &i.Text, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, goal_id, status, created, due FROM tasks
ORDER BY created DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.GoalID,
			&i.Status,
			&i.Created,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByGoal = `-- name: ListTasksByGoal :many
SELECT id, title, goal_id, status, created, due FROM tasks
WHERE goal_id = ?
ORDER BY created DESC
`

func (q *Queries) ListTasksByGoal(ctx context.Context, goalID *string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.GoalID,
			&i.Status,
			&i.Created,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, title, goal_id, status, created, due FROM tasks
WHERE status = ?
ORDER BY created DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.GoalID,
			&i.Status,
			&i.Created,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatusAndGoal = `-- name: ListTasksByStatusAndGoal :many
SELECT id, title, goal_id, status, created, due FROM tasks
WHERE status = ? AND goal_id = ?
ORDER BY created DESC
`

type ListTasksByStatusAndGoalParams struct {
	Status string
	GoalID *string
}

func (q *Queries) ListTasksByStatusAndGoal(ctx context.Context, arg ListTasksByStatusAndGoalParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatusAndGoal, arg.Status, arg.GoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.GoalID,
			&i.Status,
			&i.Created,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET status = ?, description = ?
WHERE id = ?
RETURNING id, title, description, status, created
`

type UpdateGoalParams struct {
	Status      string
	Description *string
	ID          string
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal, arg.Status, arg.Description, arg.ID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Created,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET status = ?, due = ?
WHERE id = ?
RETURNING id, title, goal_id, status, created, due
`

type UpdateTaskParams struct {
	Status string
	Due    *string
	ID     string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask, arg.Status, arg.Due, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.GoalID,
		&i.Status,
		&i.Created,
		&i.Due,
	)
	return i, err
}

const upsertSchedule = `-- name: UpsertSchedule :one
INSERT INTO schedule (date, focus, blocks)
VALUES (?, ?, ?)
ON CONFLICT(date) DO UPDATE SET
    focus = excluded.focus,
    blocks = excluded.blocks
RETURNING date, focus, blocks
`

type UpsertScheduleParams struct {
	Date   string
	Focus  string
	Blocks *string
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, upsertSchedule, arg.Date, arg.Focus, arg.Blocks)
	var i Schedule
	err := row.Scan(&i.Date, &i.Focus, &i.Blocks)
	return i, err
}
